export enum DomainErrorCode {
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  MFA_REQUIRED = "MFA_REQUIRED",
  INVITATION_EXPIRED = "INVITATION_EXPIRED",
  ALREADY_MEMBER = "ALREADY_MEMBER",
  CANNOT_REMOVE_OWNER = "CANNOT_REMOVE_OWNER",
  SUBSCRIPTION_INACTIVE = "SUBSCRIPTION_INACTIVE",
  PLAN_LIMIT_REACHED = "PLAN_LIMIT_REACHED",
  CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND",
  CONTEXT_WINDOW_EXCEEDED = "CONTEXT_WINDOW_EXCEEDED",
}
